# Generated by Django 4.2.9 on 2026-03-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="设备名称"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("router", "路由器"),
                            ("switch", "交换机"),
                            ("ap", "AP"),
                            ("ac", "AC"),
                        ],
                        max_length=20,
                        verbose_name="设备类型",
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="设备型号"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "下线"),
                            ("fault", "故障"),
                            ("preparing", "预备上线"),
                        ],
                        default="preparing",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("access", "接入层"),
                            ("aggregation", "汇聚层"),
                            ("core", "核心层"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="网络层级",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="位置描述"),
                ),
                ("ssh_port", models.IntegerField(default=22, verbose_name="SSH端口")),
                (
                    "ssh_username",
                    models.CharField(blank=True, max_length=50, verbose_name="SSH用户名"),
                ),
                (
                    "ssh_password",
                    models.CharField(blank=True, max_length=200, verbose_name="SSH密码"),
                ),
                (
                    "snmp_community",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="SNMP团体名"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后在线时间"),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="端口名称")),
                (
                    "port_type",
                    models.CharField(blank=True, max_length=20, verbose_name="端口类型"),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=20, verbose_name="端口状态"),
                ),
                (
                    "speed",
                    models.CharField(blank=True, max_length=20, verbose_name="端口速率"),
                ),
                (
                    "mac_address",
                    models.CharField(blank=True, max_length=17, verbose_name="MAC地址"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="devices.device",
                        verbose_name="所属设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "端口",
                "verbose_name_plural": "端口",
                "unique_together": {("device", "name")},
            },
        ),
    ]
