# Generated by Django 4.2.9 on 2026-03-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="latency",
            field=models.FloatField(
                blank=True, help_text="Ping测试延迟，单位毫秒", null=True, verbose_name="延迟(ms)"
            ),
        ),
    ]
