# Generated by Django 4.2.29 on 2026-03-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0002_device_latency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP地址"
            ),
        ),
    ]
