# Generated by Django 4.2.29 on 2026-04-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0003_alter_device_ip_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="snmp_community",
        ),
        migrations.AddField(
            model_name="device",
            name="gnmi_insecure",
            field=models.BooleanField(default=True, verbose_name="跳过 TLS 验证"),
        ),
        migrations.AddField(
            model_name="device",
            name="gnmi_port",
            field=models.IntegerField(default=50051, verbose_name="gNMI端口"),
        ),
    ]
