# Generated by Django 4.2.29 on 2026-04-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0005_alter_device_gnmi_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="telemetry_mode",
            field=models.CharField(
                choices=[("dial_in", "拨入拉取(Dial-in)"), ("dial_out", "拨出推送(Dial-out)")],
                default="dial_in",
                max_length=20,
                verbose_name="遥测模式",
            ),
        ),
    ]
