# Generated by Django 4.2.29 on 2026-04-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0006_device_telemetry_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="syslog_enabled",
            field=models.BooleanField(default=False, verbose_name="启用Syslog"),
        ),
        migrations.AddField(
            model_name="device",
            name="syslog_protocol",
            field=models.CharField(
                choices=[("udp", "UDP")],
                default="udp",
                max_length=10,
                verbose_name="Syslog协议",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="syslog_server_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Syslog服务器IP"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="syslog_server_port",
            field=models.IntegerField(default=10514, verbose_name="Syslog服务器端口"),
        ),
        migrations.AddField(
            model_name="device",
            name="syslog_severity_threshold",
            field=models.CharField(
                choices=[
                    ("emergency", "紧急"),
                    ("alert", "告警"),
                    ("critical", "严重"),
                    ("error", "错误"),
                    ("warning", "警告"),
                    ("notice", "通知"),
                    ("informational", "信息"),
                    ("debug", "调试"),
                ],
                default="informational",
                max_length=20,
                verbose_name="Syslog级别阈值",
            ),
        ),
    ]
