# Generated by Django 4.2.9 on 2026-03-01 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_content", models.TextField(verbose_name="配置内容")),
                (
                    "git_commit_hash",
                    models.CharField(max_length=40, verbose_name="Git Commit Hash"),
                ),
                ("commit_message", models.TextField(verbose_name="变更说明")),
                (
                    "backed_up_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="备份时间"),
                ),
                (
                    "backed_up_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_backups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="备份人",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_backups",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "配置备份",
                "verbose_name_plural": "配置备份",
                "ordering": ["-backed_up_at"],
            },
        ),
    ]
