# Generated by Django 4.2.29 on 2026-03-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configbackup",
            name="status",
            field=models.CharField(
                choices=[("success", "成功"), ("failed", "失败"), ("pending", "进行中")],
                default="success",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
