# Generated by Django 4.2.9 on 2026-03-01 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                ("variables", models.JSONField(default=dict, verbose_name="模板变量值")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已审批"),
                            ("executing", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="执行时间"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_config_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_config_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        related_name="config_tasks",
                        to="devices.device",
                        verbose_name="目标设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "配置任务",
                "verbose_name_plural": "配置任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfigTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="模板名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="模板描述")),
                (
                    "device_types",
                    models.JSONField(
                        default=list,
                        help_text='适用的设备类型列表，如 ["router", "switch"]',
                        verbose_name="适用设备类型",
                    ),
                ),
                (
                    "template_content",
                    models.TextField(help_text="Jinja2 模板内容", verbose_name="模板内容"),
                ),
                (
                    "variables_schema",
                    models.JSONField(
                        default=dict, help_text="模板变量的定义和默认值", verbose_name="变量定义"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "配置模板",
                "verbose_name_plural": "配置模板",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfigTaskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField(verbose_name="是否成功")),
                ("config_content", models.TextField(verbose_name="配置内容")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "executed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="执行时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_results",
                        to="devices.device",
                        verbose_name="目标设备",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="configs.configtask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "配置执行结果",
                "verbose_name_plural": "配置执行结果",
            },
        ),
        migrations.AddField(
            model_name="configtask",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="configs.configtemplate",
                verbose_name="配置模板",
            ),
        ),
    ]
