# Generated by Django 4.2.29 on 2026-03-21 10:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("devices", "0002_device_latency"),
        ("configs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigFetchSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="设备配置预加载", max_length=100, verbose_name="任务名称"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "exec_mode",
                    models.CharField(
                        choices=[("interval", "间隔执行"), ("cron", "定时执行")],
                        default="interval",
                        max_length=20,
                        verbose_name="执行模式",
                    ),
                ),
                (
                    "interval_seconds",
                    models.IntegerField(
                        choices=[
                            (300, "每5分钟"),
                            (600, "每10分钟"),
                            (1800, "每30分钟"),
                            (3600, "每1小时"),
                            (21600, "每6小时"),
                            (43200, "每12小时"),
                            (86400, "每24小时"),
                        ],
                        default=1800,
                        verbose_name="执行间隔(秒)",
                    ),
                ),
                (
                    "exec_time",
                    models.TimeField(default=datetime.time(2, 0), verbose_name="执行时间"),
                ),
                (
                    "exec_days",
                    models.CharField(default="*", max_length=20, verbose_name="执行日期"),
                ),
                (
                    "target_all_devices",
                    models.BooleanField(default=True, verbose_name="全部设备"),
                ),
                (
                    "only_online_devices",
                    models.BooleanField(default=True, verbose_name="仅在线设备"),
                ),
                (
                    "queue",
                    models.CharField(
                        choices=[
                            ("low", "低优先级"),
                            ("normal", "普通优先级"),
                            ("high", "高优先级"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="任务队列",
                    ),
                ),
                (
                    "max_concurrent",
                    models.IntegerField(default=5, verbose_name="最大并发数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_run_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="上次执行时间"),
                ),
                (
                    "last_run_status",
                    models.CharField(blank=True, max_length=20, verbose_name="上次执行状态"),
                ),
                (
                    "total_run_count",
                    models.IntegerField(default=0, verbose_name="总执行次数"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "target_devices",
                    models.ManyToManyField(
                        blank=True, to="devices.device", verbose_name="目标设备"
                    ),
                ),
            ],
            options={
                "verbose_name": "配置获取定时任务",
                "verbose_name_plural": "配置获取定时任务",
                "db_table": "config_fetch_schedule",
            },
        ),
        migrations.CreateModel(
            name="ConfigFetchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("partial", "部分成功"),
                            ("failed", "失败"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("total_devices", models.IntegerField(default=0, verbose_name="设备总数")),
                ("success_count", models.IntegerField(default=0, verbose_name="成功数")),
                ("failed_count", models.IntegerField(default=0, verbose_name="失败数")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "result_detail",
                    models.JSONField(blank=True, default=dict, verbose_name="执行详情"),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="configs.configfetchschedule",
                        verbose_name="定时任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "配置获取日志",
                "verbose_name_plural": "配置获取日志",
                "db_table": "config_fetch_log",
                "ordering": ["-start_time"],
            },
        ),
    ]
