# Generated by Django 4.2.29 on 2026-03-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("configs", "0003_configfetchschedule_configfetchlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configtask",
            name="approved_by",
        ),
        migrations.AddField(
            model_name="configtask",
            name="config_content",
            field=models.TextField(
                blank=True, help_text="直接输入的配置内容（设备命令）", verbose_name="配置内容"
            ),
        ),
        migrations.AddField(
            model_name="configtemplate",
            name="template_type",
            field=models.CharField(
                choices=[("device_commands", "设备命令"), ("jinja2", "Jinja2模板")],
                default="device_commands",
                max_length=20,
                verbose_name="模板类型",
            ),
        ),
        migrations.AlterField(
            model_name="configtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待执行"),
                    ("executing", "执行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="configtask",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="configs.configtemplate",
                verbose_name="配置模板",
            ),
        ),
        migrations.AlterField(
            model_name="configtemplate",
            name="template_content",
            field=models.TextField(help_text="设备命令文本或 Jinja2 模板", verbose_name="模板内容"),
        ),
        migrations.AlterField(
            model_name="configtemplate",
            name="variables_schema",
            field=models.JSONField(
                default=dict, help_text="模板变量的定义和默认值（用于 Jinja2 模式）", verbose_name="变量定义"
            ),
        ),
    ]
