# Generated by Django 4.2.29 on 2026-03-26 10:00

from django.db import migrations, models


def mark_existing_backup_schedules(apps, schema_editor):
    ConfigFetchSchedule = apps.get_model('configs', 'ConfigFetchSchedule')
    ConfigFetchSchedule.objects.filter(name='配置备份任务').update(task_type='backup')


class Migration(migrations.Migration):
    dependencies = [
        ('configs', '0004_add_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfetchschedule',
            name='device_selection_mode',
            field=models.CharField(
                choices=[('multiple', '多选'), ('single', '单选')],
                default='multiple',
                max_length=20,
                verbose_name='设备选择模式',
            ),
        ),
        migrations.AddField(
            model_name='configfetchschedule',
            name='task_type',
            field=models.CharField(
                choices=[('preload', '配置预加载'), ('backup', '配置备份')],
                default='preload',
                max_length=20,
                verbose_name='任务类型',
            ),
        ),
        migrations.RunPython(mark_existing_backup_schedules, migrations.RunPython.noop),
    ]
