# Generated by Django 4.2.9 on 2026-03-01 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("device_offline", "设备离线"),
                            ("config_failed", "配置失败"),
                            ("metric_abnormal", "指标异常"),
                            ("topology_changed", "拓扑变更"),
                        ],
                        max_length=30,
                        verbose_name="告警类型",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "紧急"),
                            ("important", "重要"),
                            ("normal", "一般"),
                        ],
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                ("message", models.TextField(verbose_name="告警信息")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活动"),
                            ("acknowledged", "已确认"),
                            ("ignored", "已忽略"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "handled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
            ],
            options={
                "verbose_name": "告警",
                "verbose_name_plural": "告警",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "status", "created_at"],
                        name="alerts_aler_device__cef58a_idx",
                    )
                ],
            },
        ),
    ]
