# Generated by Django 4.2.29 on 2026-03-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("device_offline", "设备离线"),
                    ("device_fault", "设备故障"),
                    ("config_failed", "配置失败"),
                    ("metric_abnormal", "指标异常"),
                    ("topology_changed", "拓扑变更"),
                ],
                max_length=30,
                verbose_name="告警类型",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "待处理"),
                    ("acknowledged", "已处理"),
                    ("ignored", "已忽略"),
                ],
                default="active",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
