# Generated by Django 4.2.29 on 2026-03-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cidr",
                    models.CharField(
                        help_text="例如: 192.168.1.0/24",
                        max_length=50,
                        unique=True,
                        verbose_name="网段(CIDR)",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="网段描述名称",
                        max_length=100,
                        verbose_name="名称",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "手动输入"), ("auto", "自动获取")],
                        default="manual",
                        max_length=20,
                        verbose_name="来源",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用扫描")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "网段配置",
                "verbose_name_plural": "网段配置",
                "ordering": ["cidr"],
            },
        ),
        migrations.CreateModel(
            name="IPScanTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cidr", models.CharField(max_length=50, verbose_name="扫描网段")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "扫描中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("total_ips", models.IntegerField(default=0, verbose_name="总IP数")),
                ("scanned_ips", models.IntegerField(default=0, verbose_name="已扫描数")),
                ("alive_ips", models.IntegerField(default=0, verbose_name="存活IP数")),
                ("message", models.TextField(blank=True, verbose_name="消息/错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "subnet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipmanagement.subnet",
                        verbose_name="网段",
                    ),
                ),
            ],
            options={
                "verbose_name": "扫描任务",
                "verbose_name_plural": "扫描任务",
                "ordering": ["-created_at"],
            },
        ),
    ]
