# Generated by Django 4.2.29 on 2026-03-24 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0002_device_latency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ipmanagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subnet",
            name="description",
            field=models.TextField(blank=True, help_text="网段用途描述", verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="subnet",
            name="vlan_id",
            field=models.IntegerField(
                blank=True,
                help_text="VLAN编号 (1-4094)",
                null=True,
                verbose_name="VLAN ID",
            ),
        ),
        migrations.CreateModel(
            name="IPAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(unique=True, verbose_name="IP地址"),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        help_text="DNS主机名",
                        max_length=255,
                        verbose_name="主机名",
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True,
                        help_text="例如: AA:BB:CC:DD:EE:FF",
                        max_length=17,
                        verbose_name="MAC地址",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="IP地址用途描述", verbose_name="描述"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可用"),
                            ("allocated", "已分配"),
                            ("reserved", "预留"),
                            ("dhcp", "DHCP"),
                            ("monitoring", "监控中"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "allocated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="分配时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ip_allocations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分配人",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_ips",
                        to="devices.device",
                        verbose_name="关联设备",
                    ),
                ),
                (
                    "subnet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_addresses",
                        to="ipmanagement.subnet",
                        verbose_name="所属网段",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP地址",
                "verbose_name_plural": "IP地址",
                "ordering": ["ip_address"],
                "indexes": [
                    models.Index(
                        fields=["subnet", "status"],
                        name="ipmanagemen_subnet__6a17f2_idx",
                    ),
                    models.Index(
                        fields=["hostname"], name="ipmanagemen_hostnam_7a6fff_idx"
                    ),
                    models.Index(
                        fields=["mac_address"], name="ipmanagemen_mac_add_f98b09_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AllocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, verbose_name="IP地址"),
                ),
                (
                    "hostname",
                    models.CharField(blank=True, max_length=255, verbose_name="主机名"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("allocate", "分配"),
                            ("release", "释放"),
                            ("update", "更新"),
                            ("reserve", "预留"),
                            ("scan_discover", "扫描发现"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="操作",
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, help_text="操作前的IP状态", null=True, verbose_name="旧值"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, help_text="操作后的IP状态", null=True, verbose_name="新值"
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="操作备注信息", verbose_name="备注"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ip_allocation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "分配记录",
                "verbose_name_plural": "分配记录",
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "-performed_at"],
                        name="ipmanagemen_ip_addr_d84ad4_idx",
                    )
                ],
            },
        ),
    ]
