# Generated by Django 4.2.9 on 2026-03-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("cpu", "CPU使用率"),
                            ("memory", "内存使用率"),
                            ("traffic", "端口流量"),
                            ("packet_loss", "丢包率"),
                            ("connections", "连接数"),
                        ],
                        max_length=20,
                        verbose_name="指标类型",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        help_text="如 port_eth0_traffic",
                        max_length=50,
                        verbose_name="指标名称",
                    ),
                ),
                ("value", models.FloatField(verbose_name="指标值")),
                ("unit", models.CharField(max_length=20, verbose_name="单位")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="采集时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "监控数据",
                "verbose_name_plural": "监控数据",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "metric_type", "timestamp"],
                        name="monitoring__device__a6a2b5_idx",
                    )
                ],
            },
        ),
    ]
