# Generated by Django 4.2.29 on 2026-04-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0002_alter_metricdata_metric_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metricdata",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("traffic", "端口流量"),
                    ("packet_loss", "丢包率"),
                    ("connections", "连接数"),
                    ("interface_status", "接口状态"),
                    ("interface_in_traffic", "接口入向流量"),
                    ("interface_out_traffic", "接口出向流量"),
                    ("interface_in_drops", "接口入向丢包"),
                    ("interface_out_drops", "接口出向丢包"),
                    ("ospf_neighbor", "OSPF邻居状态"),
                ],
                max_length=30,
                verbose_name="指标类型",
            ),
        ),
    ]
