# Generated by Django 4.2.9 on 2026-03-01 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("alert", "告警日志"),
                            ("system", "系统日志"),
                            ("operation", "操作日志"),
                        ],
                        max_length=20,
                        verbose_name="日志类型",
                    ),
                ),
                ("message", models.TextField(verbose_name="日志内容")),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="详细信息"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_logs",
                        to="devices.device",
                        verbose_name="相关设备",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统日志",
                "verbose_name_plural": "系统日志",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["log_type", "timestamp"],
                        name="logs_system_log_typ_dbe055_idx",
                    )
                ],
            },
        ),
    ]
