# Generated by Django 4.2.29 on 2026-04-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemlog",
            name="log_type",
            field=models.CharField(
                choices=[("alert", "告警日志"), ("system", "系统日志")],
                max_length=20,
                verbose_name="日志类型",
            ),
        ),
    ]
